spring.application.name=EventHub
spring.datasource.url=jdbc:postgresql://localhost:5432/EventHubDB
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret= 2ONOXmzxoichnzoxch82moPj9n9ASNDnolzm
jwt.expiration=3600000