spring.application.name=EventHub
spring.datasource.url=jdbc:postgresql://localhost:5432/EventHubDB
spring.datasource.username=postgres
spring.datasource.password=maribelgarcia01!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true